version: '3'
services:
  web:
    image: node:14
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm start

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
